language: java
dist: xenial
sudo: false

branches:
  except:
    - gh-pages

env:
  global:
  - secure: x8A+yQ3K/iN8maKtml5H9arQQxsjc6AgX7IfuwU8AiCxkoZKWZit25OHfVB4N6cTo16+BBF3lTgRBS4SnDhYjGrLbzlfNCyv+RN4BXIGt2p+6Vq2qgkhWP2yOeGbsySibkEG4Fd0UKzOPwkDSy0nXx8h4b9nSfRMLdE1XL6QwmJMVVOpTJxUg5eL948XWcFdqF6TRCFUijNbUoBvnCKHTMh6q9fVTRMNwKeoT0dzXxbDlxV9F82wI1XwkRSYsuuc8zy5jWoxI8kfFaIq0P+tMikYRKkEDaWIX8cQ5Cz1wXOLMuOYHKKwmTtXTw0vvKGowTDj3JO2tnZ4/qWiHSNlJyPK834VHVxN1cCamwIQ9sr72vm5TGoG9rflRCmKemJgLPswAP1KmWTvX6t1UhLCngkscxcKbJxMMgdqCmYWG/rjX8wtUk2QaPcr7d0xswc8Ozqy8MlBmkkghjj1Z9fS5aT/wH+mf59E12DlKZbtimqqrs4a2Tm1QN0u4sLsO1se1VBnW8+abB+z6WrmuIn6H3xj3NULrSm9a6Dgn20ytkDZyyzy0GMRazXr4hzjusS0ifNJ2PWljOSxsuIU8qZAqEh+vsf75+ERJ2hJ654r6NcmiHBxkpmAMcUkhsRinG11wN1n37fAiLGVybglPfDCygJozr9dBIMUk+Q1aa4Y9K4=

addons:
  apt:
    update: true

matrix:
  include:
    - name: "Java 8 Tests"
      jdk: openjdk8
      env: TESTENV=tests
      script: mvn test
    - name: "GitHub Pages"
      jdk: openjdk8
      env: TESTENV=cover FYI="this also builds documentation for tags"
      script: '[[ -n "$TRAVIS_TAG" ]] && ./deploy-docs.sh || true'
      addons:
        apt:
          packages:
            - python3
            - python3-pip
            - python-virtualenv
            - make

after_success:
  - '[[ "$TESTENV" == "tests" ]] && bash <(curl -s https://codecov.io/bash) -f engine.io-server-coverage/target/site/jacoco-aggregate/jacoco.xml'

cache:
  directories:
  - $HOME/.m2
